// <auto-generated />
using System;
using ControleDeProdutos_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = ControleDeProdutos_API.Data.AppContext;

#nullable disable

namespace ControleDeProdutos_API.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220511182727_TabelasItemCategoria")]
    partial class TabelasItemCategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleDeProdutos_API.Models.Categoria", b =>
                {
                    b.Property<long?>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("familia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("codigo");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ControleDeProdutos_API.Models.Item", b =>
                {
                    b.Property<long?>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("categoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("lote")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("codigo");

                    b.HasIndex("categoriaId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ControleDeProdutos_API.Models.Item", b =>
                {
                    b.HasOne("ControleDeProdutos_API.Models.Categoria", "Categoria")
                        .WithMany("Item")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControleDeProdutos_API.Models.Categoria", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
